# -*- coding: utf-8 -*-
"""data_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uh4uR6GjYRtodK2N7Ja_MZRDOYME3Vwa
"""

df = pd.read_csv('/content/cdc_train.csv')

df.head()

import os
import time
import requests
import pandas as pd

# ---------------- CONFIG ----------------
MAPBOX_TOKEN = "pk.eyJ1IjoicmlzaGl0YWExMjMiLCJhIjoiY21qYjN6eGhsMGFzcDNjcXJwMW5qMmZ4YiJ9.D531N9kivFCVO3P9xeY-lA"
ZOOM = 16
IMG_SIZE = 256  # Mapbox supports up to 1280
CSV_PATH = "/cdc_train.csv"
OUT_DIR = "data/satellite_imagess"

# Ensure output directory exists
os.makedirs(OUT_DIR, exist_ok=True)

def download_images():
    # 1. Load Data
    try:
        df = pd.read_csv(CSV_PATH)
        print(f"Successfully loaded {len(df)} rows from {CSV_PATH}")
    except Exception as e:
        print(f"Error loading CSV: {e}")
        return

    # 2. Use a Session for better performance
    with requests.Session() as session:
        for i, row in df.iterrows():
            pid = row["id"]
            lat = row["lat"]
            lon = row["long"]

            out_path = os.path.join(OUT_DIR, f"{pid}.png")

            # Skip if image already exists
            if os.path.exists(out_path):
                continue

            # Mapbox Static API URL
            # Format: {lon},{lat},{zoom},{bearing},{pitch}/{width}x{height}
            url = (
                f"https://api.mapbox.com/styles/v1/mapbox/satellite-v9/static/"
                f"{lon},{lat},{ZOOM},0,0/{IMG_SIZE}x{IMG_SIZE}"
                f"?access_token={MAPBOX_TOKEN}"
            )

            try:
                response = session.get(url, timeout=15)

                if response.status_code == 200:
                    with open(out_path, "wb") as f:
                        f.write(response.content)
                elif response.status_code == 401:
                    print("Error: Invalid Mapbox Token.")
                    break
                elif response.status_code == 429:
                    print("Rate limit reached. Sleeping for 10 seconds...")
                    time.sleep(10)
                else:
                    print(f"Row {i} (ID {pid}): HTTP {response.status_code}")

            except Exception as e:
                print(f"Failed to download ID {pid}: {e}")

            # Progress monitoring
            if i % 100 == 0 and i > 0:
                print(f"Progress: {i} images processed...")

            # Small delay to stay within free-tier rate limits
            time.sleep(0.1)

    print("\nExtraction process complete.")

if __name__ == "__main__":
    download_images()

import os
import cv2

img_dir = "data/satellite_imagess"
files = os.listdir(img_dir)

print("Total images:", len(files))

# Try opening one image
sample = cv2.imread(os.path.join(img_dir, files[0]))
print("Sample image shape:", sample.shape)











